### ISSUE TITLE
Padding between cursor and input box bottom line

### ISSUE THREAD

**Issue by prasun89** [codeartisan-ui/material-textfields#1]
Hi CodeArtisan,
                         I have seen your material-textfields's output in the browser. It is a great work done by you. But I think there should be padding between cursor and input box's bottom line. I will request you to pay attention again in Google Material Design Textfield's document. It will better help you to understand what I want to say.
![screen shot 2017-08-03 at 4 45 27 pm](https://user-images.githubusercontent.com/26485699/28919480-52a27744-786b-11e7-801d-f72cf6ce48e0.png)
Thanks,
Have a nice day

**Comment by prakashpie** [comment]
we are working on this issue.. we will notify you once it has been done.. thank you for posting issue

**Comment by prakashpie** [comment]
## bug fixed @prasun89

**Comment by prasun89** [comment]
Thanks Mr. Prakash Bharti.
